name: Go

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:

  format-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18rc1
    - name: Format 
      run: gofmt -l -s -w ./
    - name: Lint
      run:  go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...
    - name: Test
      run: go test ./... --cover
    
